url_prefix:
katex_output: true

repository:
  url: https://github.com/coursesproject/courses-template-default

outputs:
  - html:
  - notebook:

preprocessors:
  - name: exercises

notebook_meta:
  kernelspec:
    display_name: Python
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python