url_prefix: /
katex_output: true



repository:
  url: https://github.com/antonmeskildsen/courses/tree/main/docs

outputs:
  - html
  - notebook

parsers:
  html:
    settings:
      solutions: false
      notebook_outputs: true
    md_processors:
      - type: shortcodes
      - type: katex
    ast_processors:
      - type: exercises
  notebook:
    settings:
      solutions: false
      notebook_outputs: true
    md_processors:
      - type: shortcodes
    ast_processors:
      - type: exercises
